'use client'

import { motion } from 'framer-motion'
import { Shield, Heart, Users, Bot } from 'lucide-react'
import type { SourceQuality as SourceQualityType } from '@/types/classification'

interface SourceQualityProps {
  sourceQuality: SourceQualityType
  score: number
}

const sourceConfig: Record<
  SourceQualityType,
  {
    icon: typeof Shield
    label: string
    color: string
    bgClass: string
    borderClass: string
    barClass: string
    description: string
    maxScore: number
  }
> = {
  government: {
    icon: Shield,
    label: 'Government Source',
    color: '#10b981',
    bgClass: 'bg-emerald-500/10',
    borderClass: 'border-emerald-500/20',
    barClass: 'bg-emerald-500',
    description:
      'This resource comes from an official government database (e.g., Benefits.gov, HUD, SAMHSA). Government sources are regularly audited and represent the highest reliability tier.',
    maxScore: 95,
  },
  nonprofit: {
    icon: Heart,
    label: 'Nonprofit Organization',
    color: '#3b82f6',
    bgClass: 'bg-blue-500/10',
    borderClass: 'border-blue-500/20',
    barClass: 'bg-blue-500',
    description:
      'This resource is provided by a verified nonprofit organization, such as United Way 211 partners. Nonprofits are subject to oversight and community accountability.',
    maxScore: 85,
  },
  community: {
    icon: Users,
    label: 'Community Resource',
    color: '#f59e0b',
    bgClass: 'bg-amber-500/10',
    borderClass: 'border-amber-500/20',
    barClass: 'bg-amber-500',
    description:
      'This resource comes from community-contributed data. While valuable and often locally accurate, community sources have less formal verification than government or nonprofit sources.',
    maxScore: 70,
  },
  ai_generated: {
    icon: Bot,
    label: 'AI-Generated',
    color: '#6b7280',
    bgClass: 'bg-gray-500/10',
    borderClass: 'border-gray-500/20',
    barClass: 'bg-gray-400',
    description:
      'This classification was generated by our AI model and has not been independently verified by a human. We recommend confirming details with the resource provider directly.',
    maxScore: 50,
  },
}

export function SourceQuality({ sourceQuality, score }: SourceQualityProps) {
  const config = sourceConfig[sourceQuality]
  const Icon = config.icon

  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4 }}
      className="space-y-5"
    >
      {/* Source type header */}
      <div className="flex items-center gap-4">
        <div
          className={`w-12 h-12 rounded-xl flex items-center justify-center ${config.bgClass} border ${config.borderClass}`}
        >
          <Icon className="w-6 h-6" style={{ color: config.color }} />
        </div>
        <div>
          <h4 className="text-base font-semibold text-white/90">{config.label}</h4>
          <p className="text-xs text-white/40 mt-0.5">Source quality score</p>
        </div>
      </div>

      {/* Quality score bar */}
      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <span className="text-xs text-white/50 font-medium">Quality Score</span>
          <span className="text-sm font-bold tabular-nums" style={{ color: config.color }}>
            {score}%
          </span>
        </div>
        <div className="h-2.5 w-full rounded-full overflow-hidden bg-white/10">
          <motion.div
            className={`h-full rounded-full ${config.barClass}`}
            initial={{ width: 0 }}
            animate={{ width: `${score}%` }}
            transition={{ duration: 1, ease: [0.25, 0.46, 0.45, 0.94] }}
          />
        </div>
      </div>

      {/* Source tier comparison */}
      <div className="space-y-2">
        <p className="text-[10px] uppercase tracking-wider text-white/30 font-semibold">
          Source reliability tiers
        </p>
        {(['government', 'nonprofit', 'community', 'ai_generated'] as const).map((tier) => {
          const tierConfig = sourceConfig[tier]
          const isActive = tier === sourceQuality
          return (
            <div key={tier} className="flex items-center gap-3">
              <div
                className={`w-1.5 h-1.5 rounded-full shrink-0 ${isActive ? 'opacity-100' : 'opacity-30'}`}
                style={{ backgroundColor: tierConfig.color }}
              />
              <span
                className={`text-xs flex-1 ${isActive ? 'text-white/80 font-semibold' : 'text-white/35'}`}
              >
                {tierConfig.label}
              </span>
              <span
                className={`text-xs tabular-nums ${isActive ? 'font-bold' : 'font-normal text-white/30'}`}
                style={{ color: isActive ? tierConfig.color : undefined }}
              >
                {tierConfig.maxScore}%
              </span>
            </div>
          )
        })}
      </div>

      {/* Description */}
      <div
        className="rounded-xl p-4 border"
        style={{
          backgroundColor: `${config.color}08`,
          borderColor: `${config.color}20`,
        }}
      >
        <p className="text-sm text-white/70 leading-relaxed">{config.description}</p>
      </div>
    </motion.div>
  )
}

export default SourceQuality
